/**
 * PIVISION Mobile — Capacitor configuration
 *
 * Stage 6 of the modernization plan. Replaces the legacy Cordova
 * shell that produced the original `PIV-v4.2.0-R300u-tested.apk`.
 *
 * Package ID and version mirror the legacy AndroidManifest.xml so
 * upgrade installs from the old APK will work in place. (The legacy
 * APK was built from `com.pivision.qa` v4.2.0; bumping to a new
 * package ID would be perceived as a fresh app install.)
 *
 * The web layer that gets bundled into the Android project lives at
 * `www/`, populated by `npm run cap:prepare` (see scripts/cap-prepare.mjs).
 * That script copies the raw `www-src/` tree — NOT the Vite-bundled
 * `dist/` — because:
 *   1. The legacy bundles in `www-src/js/` are classic IIFE scripts
 *      that Vite cannot losslessly bundle into ES modules without
 *      load-order rewrites (see stage 5 e2e investigation).
 *   2. The static raw tree is the same shape the original APK uses,
 *      so an in-place upgrade install behaves identically.
 *   3. Future stages can switch this to `dist/` once the legacy
 *      modules have been migrated to real ES modules.
 *
 * The native `android/` directory is *not* committed — it's
 * regenerated by `npx cap add android` (one-time) and refreshed by
 * `npx cap sync` from this config.
 */

import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.pivision.qa',
  appName: 'PIVISION QA',
  webDir: 'www',
  bundledWebRuntime: false,
  // Allow the web layer to talk to PI Web API endpoints over HTTP/HTTPS.
  // The legacy APK shipped with `usesCleartextTraffic="true"` so plain
  // HTTP works against on-prem PI servers; we mirror that to keep
  // upgrade installs functional.
  android: {
    allowMixedContent: true,
    captureInput: true,
    webContentsDebuggingEnabled: true,
    minWebViewVersion: 60,
  },
  server: {
    androidScheme: 'https',
    // The legacy app uses `index.html` as its mobile entry point.
    // Capacitor honors this when launching the WebView.
    iosScheme: 'capacitor',
  },
};

export default config;
